In [1]:
import tensorflow as tf
from os import getcwd

data_loc = f"{getcwd()}/mnist.npz"

Desired_acc = 0.99
class myCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs={}):
        if (logs.get('accuracy') is not None and logs.get('accuracy') >= Desired_acc): 
            print("\nReached 99% accuracy so cancelling training!")
            self.model.stop_training = True


# GRADED FUNCTION: train_mnist
def train_mnist():

    callbacks = myCallback()
   
    mnist = tf.keras.datasets.mnist
    (x_train, y_train), (x_test, y_test) = mnist.load_data(path=data_loc)   # training set : test set = ~85 : ~15  
    print(len(x_train), len(y_train), len(x_test), len(y_test))
    
    x_train = x_train / 255.0
    x_test = x_test / 255.0
 
    model = tf.keras.models.Sequential([
       
        tf.keras.layers.Flatten(),
        tf.keras.layers.Dense(1024, activation=tf.nn.relu),
        tf.keras.layers.Dense(10, activation=tf.nn.softmax)
        
    ])

    model.compile(optimizer='adam',
                  loss='sparse_categorical_crossentropy',
                  metrics=['accuracy'])

    
    history = model.fit(  
        x_train, y_train, epochs=10, callbacks=[callbacks]      
    )

    return history.epoch, history.history['accuracy'][-1]


train_mnist()


60000 60000 10000 10000
Metal device set to: Apple M1 Pro
Epoch 1/10


2022-03-17 14:10:17.665978: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-03-17 14:10:17.666380: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)
2022-03-17 14:10:17.840813: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-03-17 14:10:18.225251: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


1875/1875 [==============================] - 11s 5ms/step - loss: 0.1843 - accuracy: 0.9452
Epoch 2/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0754 - accuracy: 0.9764
Epoch 3/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0479 - accuracy: 0.9848
Epoch 4/10
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0344 - accuracy: 0.9890
Epoch 5/10
1869/1875 [============================>.] - ETA: 0s - loss: 0.0261 - accuracy: 0.9912
Reached 99% accuracy so cancelling training!
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0261 - accuracy: 0.9912


([0, 1, 2, 3, 4], 0.991183340549469)

In [5]:
import numpy as np
data = np.load(f"{getcwd()}/mnist.npz")
lst = data.files
for item in lst:
    print(item)
    print(data[item])

x_test
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
x_train
[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 